- hosts: all
  remote_user: centos
  become: true
  become_method: sudo
  become_user: root
  tasks:
   - name: create a user
     user:
       name: user1
       state: present
       shell: /bin/bash
       home: /home/user1
