- name: myplay
  hosts: all
  tasks:
      - name: Create file
        file:
            path: /tmp/hello
            state: touch
 
- name: second play
  hosts: all
  sudo: yes
  tasks:
      - name: Create user
        user:
            name: mario
            shell: /bin/zsh
 
      - name: Install tree
        yum:
            name: tree
            state: latest
